name: foodgallery
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

  #  sdk: ">=2.1.0 <3.0.0"
  # sdk: ">=2.2.2 <3.0.0"

  #  - sdk: ">=2.1.0 <3.0.0" // changed on may 9 2020.
  #  + sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #  flutter_neumorphic: ^2.0.1
  flutter_neumorphic: ^3.0.1
  #  google_fonts: ^1.0.0
  #  path_provider: '>=1.0.0 <2.0.0'
#  path_provider: ^1.6.11
  #  cloud_firestore: ^0.13.5
  cloud_firestore: ^0.13.7

  #  firebase_core: ^0.4.0+9,
  #  firebase_core: ^0.4.5

  #  firebase_auth: ^0.16.0
  firebase_auth: ^0.16.1

  #  firebase_auth: ^0.14.0+5
  #  firebase_storage: ^3.1.5
  firebase_storage: ^3.1.6
  #  google_sign_in: ^4.4.4
  #  google_sign_in: ^4.5.1
  #  neumorphic: ^0.3.0
  #  neumorphic: ^0.3.2
  #  image_picker_gallery_camera: ^0.1.4
  #  shared_preferences: ^0.5.7
  shared_preferences: ^0.5.7+3
  #  flutter_spinkit: ^4.1.2+1
  logger: ^0.9.1
  #  cached_network_image: ^2.2.0
  cached_network_image: ^2.2.0+1
  #  random_color: ^1.0.5
  font_awesome_flutter: ^8.8.1
#  esc_pos_printer: ^3.2.5
#  esc_pos_utils: ^0.4.5
  ping_discover_network: ^0.2.0+1
  wifi: ^0.1.5
  intl: ^0.16.1
  oktoast: ^2.3.2
  platform_action_sheet: ^0.0.3
  esc_pos_bluetooth: ^0.2.8
  dotted_border: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/flutterlogo.svg
     - assets/Group520.png
     - assets/icons8atv100.png
     - assets/icons8bigparcel100.png
     - assets/icons8cyclingmountainbike100.png
     - assets/icons8delivery96.png
     - assets/icons8facebooklike100.png
     - assets/icons8hand100.png
     - assets/icons8openparcel100.png
     - assets/icons8phone100.png
     - assets/icons8restaurantbuilding100.png
     - assets/icons8restauranttable100.png
     - assets/icons8ringingphone100.png
     - assets/icons8speakerphone100.png
     - assets/icons8waiter100.png
     - assets/Path2008.png



#    - assets/images/logo.png
#    - assets/images/powered_by.png
#    - assets/images/email_icon.png
#    - assets/images/password_icon.png
#    - assets/images/user_icon.png
#    - assets/images/as.png
#    - assets/Path2008.png



#    - assets/images/Path2008.png
#    - assets/Group520.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GreatVibes-Regular
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
          style: italic
    - family: Itim-Regular
      fonts:
        - asset: fonts/Itim-Regular.ttf
          style: normal
    - family: Poppins-ExtraBold
      fonts:
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          style: normal
    - family: PatrickHand-Regular
      fonts:
        - asset: fonts/Patrick_Hand/PatrickHand-Regular.ttf
          style: normal

  #    - family: Tangerine
  #      fonts:
  #        - asset: fonts/Tangerine-Bold.ttf
  #        - asset: fonts/Tangerine-Regular.ttf
  #          weight: 800
  #          style: italic


  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  #     - family: Schyler
  #       fonts:
  #         - asset: fonts/Schyler-Regular.ttf
  #         - asset: fonts/Schyler-Italic.ttf
  #           style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
